[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "literary-graph-rag"
version = "0.1.0"
description = "Knowledge graph companion for literary analysis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ebooklib",
    "beautifulsoup4"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]